# Generated by Django 5.2.7 on 2025-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_precios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_acero',
            field=models.CharField(choices=[('304', '304'), ('304L', '304L'), ('316', '316'), ('316L', '316L')], max_length=20),
        ),
    ]
