# Generated by Django 5.2.7 on 2025-11-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_tipo_acero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='grosor',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_acero',
            field=models.CharField(choices=[('304', '304'), ('304L', '304L'), ('316', '316'), ('316L', '316L'), ('Viton', 'Viton'), ('Silicona', 'Silicona')], max_length=20),
        ),
    ]
