# Generated by Django 5.2.7 on 2025-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_update_tipo_acero_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado_preparacion',
            field=models.CharField(blank=True, choices=[('iniciada', 'Iniciada'), ('embalando', 'Embalando tus productos'), ('listo_retiro', 'Listo para retiro!')], default='iniciada', help_text='Estado de preparación del pedido para retiro en tienda', max_length=20, null=True),
        ),
    ]
