# Generated by Django 5.2.7 on 2025-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_producto_ancho_remove_producto_grosor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento de la cotización (7 días desde creación)', null=True),
        ),
    ]
