# Generated by Django 5.2.7 on 2025-11-20 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_producto_ancho_remove_producto_grosor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta cotización (trabajador/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
