# Generated by Django 5.2.7 on 2025-11-20 03:06

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_add_creado_por_to_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='grosor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='largo',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado_sii',
            field=models.CharField(blank=True, help_text='Estado del documento en el SII', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='facturada',
            field=models.BooleanField(default=False, help_text='Indica si se ha emitido el documento tributario'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='facturado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que emitió el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_facturadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de emisión del documento tributario', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='folio_sii',
            field=models.CharField(blank=True, help_text='Folio asignado por el SII', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de folio del documento tributario', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pdf_documento',
            field=models.FileField(blank=True, help_text='PDF del documento tributario', null=True, storage=storages.backends.s3.S3Storage(), upload_to='documentos_tributarios/'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta Electrónica'), ('factura', 'Factura Electrónica')], help_text='Tipo de documento tributario emitido', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='track_id_sii',
            field=models.CharField(blank=True, help_text='Track ID del envío al SII', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='xml_dte',
            field=models.TextField(blank=True, help_text='XML del DTE generado', null=True),
        ),
    ]
