# Generated by Django 5.2.7 on 2025-11-20 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_producto_ancho_remove_producto_grosor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion', models.CharField(blank=True, max_length=20, unique=True)),
                ('proveedor', models.CharField(help_text='Nombre del proveedor', max_length=200)),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50)),
                ('fecha_factura', models.DateField(blank=True, help_text='Fecha de la factura del proveedor', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la recepción')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compras',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad recibida')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra unitario', max_digits=10, null=True)),
                ('lote', models.CharField(blank=True, help_text='Número de lote del proveedor', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre este producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.recepcioncompra')),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
            },
        ),
    ]
