# Generated by Django 5.2.7 on 2025-11-21 20:29

import apps.tienda.models
import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_recepcioncompra_detallerecepcioncompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.tienda.models.producto_imagen_path),
        ),
        migrations.CreateModel(
            name='VentaN8n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_preference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mercadopago_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('items', models.JSONField(default=list, help_text='Lista de productos comprados')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional de la venta')),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_n8n', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta N8N',
                'verbose_name_plural': 'Ventas N8N',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['mercadopago_preference_id'], name='tienda_vent_mercado_3e6fa0_idx'), models.Index(fields=['mercadopago_payment_id'], name='tienda_vent_mercado_3d9409_idx'), models.Index(fields=['email_comprador'], name='tienda_vent_email_c_1ec881_idx')],
            },
        ),
    ]
