# Generated by Django 5.2.7 on 2025-11-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_cotizacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='creado_por_nombre',
            field=models.CharField(blank=True, help_text='Nombre del creador (se preserva si el usuario es eliminado)', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_email',
            field=models.EmailField(blank=True, help_text='Email del usuario (se preserva si el usuario es eliminado)', max_length=254),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre del usuario (se preserva si el usuario es eliminado)', max_length=200),
        ),
    ]
