# Generated by Django 5.2.7 on 2025-11-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion_comercial',
            field=models.TextField(blank=True, help_text='Dirección comercial de la empresa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='giro',
            field=models.CharField(blank=True, help_text='Giro o actividad comercial', max_length=200),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social de la empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT de persona natural o empresa', max_length=12),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_cliente',
            field=models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa')], default='persona', help_text='Tipo de cliente para facturación', max_length=20),
        ),
    ]
